"""create Concert model

Revision ID: e9c2031b7a31
Revises: dd388c9e49ce
Create Date: 2024-09-21 13:28:32.271132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c2031b7a31'
down_revision: Union[str, None] = 'dd388c9e49ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concerts',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['bands.id'], ),
    sa.PrimaryKeyConstraint('band_id', 'venue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concerts')
    # ### end Alembic commands ###
